### PR TITLE
Use cdnjs for angular.js

### PR DESCRIPTION
**Pull request by ojhaujjwal**
Google cdn does not work in China. So, I can't view the demo from China.

### CODE REVIEW

**Comment by jacobscarter** [comment]
Can you update the PR to fix merge conflicts please.

**Comment by jacobscarter** [comment]
@ojhaujjwal this is outdated, in gh-pages we use a local copy of angular now.

**Comment by jimaek** [comment]
@jacobscarter Hey, if you want you can use jsDelivr which pulls files directly from npm instantly

**Comment by jimaek** [comment]
@jsdelivrbot npm angular-wizard

**Comment by jacobscarter** [comment]
@jimaek thanks for the info, we have jsdeliver listed as CDN in the README, for the gh-pages we will just leave it pulling locally, that way there wont be any domain access issues for anyone

**Pull request closed without merging**
