### PR TITLE
Common.js module wrapper

### PR DESCRIPTION
**Pull request by dreef3**
Wrapper to use as common.js module. To use with Webpack, Browserify and similar tools. Example:

```
angular.module('myApp, [
    require('angular-wizard')
]);
```

### CODE REVIEW

**Comment by mykz** [comment]
@dreef3 I get a reference error when trying out your branch. Looks like angular can't reference lowdash...

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by jacobscarter** [comment]
@dreef3 Can you fix merge conflicts and remove the `/dist` files from your PR

**Comment by blanco217** [comment]
@dreef3 I would like to use this module with webpack. Any status on fixing this?

**Pull request closed without merging**
